alias arilog="$HOME/.arisaka_root/bin/arisaka/arilog"

export ARILOG_NS='zsh-startup'
arilog -i "sourcing zprofile"

arilog -i "sourcing arisaka environment variables"
while read -r line; do
    eval "export $line"
done < <("$HOME/.arisaka_root/arisaka_init")

arilog -i "setting user base dirs"
while read -r line; do
    eval "export $line"
done < <("$ARISAKA_BIN/shell/user-dirs")

# Tell zsh where to find the remainder of its config.
export ZDOTDIR="$ARISAKA_ETC/zsh"

arilog -i "done sourcing zprofile"
unset ARILOG_NS

# vim: set ft=zsh:
